spring.application.name=pedidos-service
server.port=8082

# URL del servicio de inventario (a dónde publicamos los eventos)
inventario.url=http://localhost:8083

springdoc.swagger-ui.path=/swagger-ui.html
